---
services:

  # --- SABnzbd - Usenet downloader
  init-sabnzbd:
    container_name: init-sabnzbd
    image: debian:stable-slim
    restart: "no"
    entrypoint: ["/bin/bash", "-c"]
    command: ["ls -al /setup && ls -al /config && cp -f /setup/sabnzbd.ini /config"]
    env_file: .env
    volumes:
      - /mnt/data/appdata/sabnzbd:/config:rw
      - ./config/sabnzbd:/setup

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/data/appdata/sabnzbd:/config:rw
      - /mnt/data/media/downloads/incomplete:/incomplete-downloads:rw
      - /mnt/data/media/downloads:/downloads:rw
      - /mnt/data/media/backup/sabnzbd:/backup:rw
    ports:
      - 8008:8080
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.entrypoints=http"
      - "traefik.http.routers.sabnzbd.rule=Host(`media.moerman.online`) && PathPrefix(`/nzb`)"
      - "traefik.http.middlewares.sabnzbd-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sabnzbd.middlewares=sabnzbd-https-redirect"
      - "traefik.http.routers.sabnzbd-secure.entrypoints=https"
      - "traefik.http.routers.sabnzbd-secure.rule=Host(`media.moerman.online`) && PathPrefix(`/nzb`)"
      - "traefik.http.routers.sabnzbd-secure.middlewares=authentik@file"
      - "traefik.http.routers.sabnzbd-secure.tls=true"
      - "traefik.http.routers.sabnzbd.service=sabnzbd"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"

networks:
  frontend:
    external: true